version: "3"

services:
  manhattan:
    build: .
    volumes:
      - ./roomhub.db:/usr/src/app/roomhub.db
      - /home/ops/certs:/usr/src/app/server/certs
    ports:
      - 9081:8080
      - 9082:9229
    restart: unless-stopped